allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msgpackr-extract: true
  sharp: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lightningcss
  - lmdb
  - msgpackr-extract
  - sharp
