/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuarioRouteRouteImport } from './routes/usuario/route'
import { Route as ReportesRouteRouteImport } from './routes/reportes/route'
import { Route as FilesRouteRouteImport } from './routes/files/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsuarioIndexRouteImport } from './routes/usuario/index'
import { Route as ReportesIndexRouteImport } from './routes/reportes/index'
import { Route as MoneyIndexRouteImport } from './routes/money/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as UsuarioChar91idChar93RouteRouteImport } from './routes/usuario/[$id]/route'
import { Route as UsuarioChar91idChar93IndexRouteImport } from './routes/usuario/[$id]/index'
import { Route as FilesUnusedIndexRouteImport } from './routes/files/unused.index'
import { Route as FilesTecnicosIndexRouteImport } from './routes/files/tecnicos.index'
import { Route as FilesRepetidasIndexRouteImport } from './routes/files/repetidas.index'
import { Route as UsuarioChar91idChar93ReportesIndexRouteImport } from './routes/usuario/[$id]/reportes.index'
import { Route as UsuarioChar91idChar93InstrumentosIndexRouteImport } from './routes/usuario/[$id]/instrumentos.index'
import { Route as UsuarioChar91idChar93EmpresasIndexRouteImport } from './routes/usuario/[$id]/empresas.index'
import { Route as UsuarioChar91idChar93CreditosIndexRouteImport } from './routes/usuario/[$id]/creditos.index'
import { Route as UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRouteImport } from './routes/usuario/[$id]/reportes/[$reporteId]/pdf-reducida'
import { Route as UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRouteImport } from './routes/usuario/[$id]/reportes/[$reporteId]/pdf'
import { Route as UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteImport } from './routes/usuario/[$id]/reportes/[$reporteId]/_header/route'
import { Route as UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRouteImport } from './routes/usuario/[$id]/reportes/[$reporteId]/_header/resumen.index'
import { Route as UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRouteImport } from './routes/usuario/[$id]/reportes/[$reporteId]/_header/general.index'
import { Route as UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRouteImport } from './routes/usuario/[$id]/reportes/[$reporteId]/_header/areas.index'

const UsuarioRouteRoute = UsuarioRouteRouteImport.update({
  id: '/usuario',
  path: '/usuario',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRouteRoute = ReportesRouteRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRouteRoute = FilesRouteRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuarioIndexRoute = UsuarioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsuarioRouteRoute,
} as any)
const ReportesIndexRoute = ReportesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportesRouteRoute,
} as any)
const MoneyIndexRoute = MoneyIndexRouteImport.update({
  id: '/money/',
  path: '/money/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilesRouteRoute,
} as any)
const UsuarioChar91idChar93RouteRoute =
  UsuarioChar91idChar93RouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => UsuarioRouteRoute,
  } as any)
const UsuarioChar91idChar93IndexRoute =
  UsuarioChar91idChar93IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UsuarioChar91idChar93RouteRoute,
  } as any)
const FilesUnusedIndexRoute = FilesUnusedIndexRouteImport.update({
  id: '/unused/',
  path: '/unused/',
  getParentRoute: () => FilesRouteRoute,
} as any)
const FilesTecnicosIndexRoute = FilesTecnicosIndexRouteImport.update({
  id: '/tecnicos/',
  path: '/tecnicos/',
  getParentRoute: () => FilesRouteRoute,
} as any)
const FilesRepetidasIndexRoute = FilesRepetidasIndexRouteImport.update({
  id: '/repetidas/',
  path: '/repetidas/',
  getParentRoute: () => FilesRouteRoute,
} as any)
const UsuarioChar91idChar93ReportesIndexRoute =
  UsuarioChar91idChar93ReportesIndexRouteImport.update({
    id: '/reportes/',
    path: '/reportes/',
    getParentRoute: () => UsuarioChar91idChar93RouteRoute,
  } as any)
const UsuarioChar91idChar93InstrumentosIndexRoute =
  UsuarioChar91idChar93InstrumentosIndexRouteImport.update({
    id: '/instrumentos/',
    path: '/instrumentos/',
    getParentRoute: () => UsuarioChar91idChar93RouteRoute,
  } as any)
const UsuarioChar91idChar93EmpresasIndexRoute =
  UsuarioChar91idChar93EmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => UsuarioChar91idChar93RouteRoute,
  } as any)
const UsuarioChar91idChar93CreditosIndexRoute =
  UsuarioChar91idChar93CreditosIndexRouteImport.update({
    id: '/creditos/',
    path: '/creditos/',
    getParentRoute: () => UsuarioChar91idChar93RouteRoute,
  } as any)
const UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRoute =
  UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRouteImport.update(
    {
      id: '/reportes/$reporteId/pdf-reducida',
      path: '/reportes/$reporteId/pdf-reducida',
      getParentRoute: () => UsuarioChar91idChar93RouteRoute,
    } as any,
  )
const UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRoute =
  UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRouteImport.update({
    id: '/reportes/$reporteId/pdf',
    path: '/reportes/$reporteId/pdf',
    getParentRoute: () => UsuarioChar91idChar93RouteRoute,
  } as any)
const UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRoute =
  UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteImport.update(
    {
      id: '/reportes/$reporteId/_header',
      path: '/reportes/$reporteId',
      getParentRoute: () => UsuarioChar91idChar93RouteRoute,
    } as any,
  )
const UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRoute =
  UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRouteImport.update(
    {
      id: '/resumen/',
      path: '/resumen/',
      getParentRoute: () =>
        UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRoute,
    } as any,
  )
const UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRoute =
  UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRouteImport.update(
    {
      id: '/general/',
      path: '/general/',
      getParentRoute: () =>
        UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRoute,
    } as any,
  )
const UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRoute =
  UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRouteImport.update(
    {
      id: '/areas/',
      path: '/areas/',
      getParentRoute: () =>
        UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRouteRouteWithChildren
  '/reportes': typeof ReportesRouteRouteWithChildren
  '/usuario': typeof UsuarioRouteRouteWithChildren
  '/usuario/$id': typeof UsuarioChar91idChar93RouteRouteWithChildren
  '/files/': typeof FilesIndexRoute
  '/money/': typeof MoneyIndexRoute
  '/reportes/': typeof ReportesIndexRoute
  '/usuario/': typeof UsuarioIndexRoute
  '/files/repetidas/': typeof FilesRepetidasIndexRoute
  '/files/tecnicos/': typeof FilesTecnicosIndexRoute
  '/files/unused/': typeof FilesUnusedIndexRoute
  '/usuario/$id/': typeof UsuarioChar91idChar93IndexRoute
  '/usuario/$id/creditos/': typeof UsuarioChar91idChar93CreditosIndexRoute
  '/usuario/$id/empresas/': typeof UsuarioChar91idChar93EmpresasIndexRoute
  '/usuario/$id/instrumentos/': typeof UsuarioChar91idChar93InstrumentosIndexRoute
  '/usuario/$id/reportes/': typeof UsuarioChar91idChar93ReportesIndexRoute
  '/usuario/$id/reportes/$reporteId': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteWithChildren
  '/usuario/$id/reportes/$reporteId/pdf': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRoute
  '/usuario/$id/reportes/$reporteId/pdf-reducida': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRoute
  '/usuario/$id/reportes/$reporteId/areas/': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRoute
  '/usuario/$id/reportes/$reporteId/general/': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRoute
  '/usuario/$id/reportes/$reporteId/resumen/': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesIndexRoute
  '/money': typeof MoneyIndexRoute
  '/reportes': typeof ReportesIndexRoute
  '/usuario': typeof UsuarioIndexRoute
  '/files/repetidas': typeof FilesRepetidasIndexRoute
  '/files/tecnicos': typeof FilesTecnicosIndexRoute
  '/files/unused': typeof FilesUnusedIndexRoute
  '/usuario/$id': typeof UsuarioChar91idChar93IndexRoute
  '/usuario/$id/creditos': typeof UsuarioChar91idChar93CreditosIndexRoute
  '/usuario/$id/empresas': typeof UsuarioChar91idChar93EmpresasIndexRoute
  '/usuario/$id/instrumentos': typeof UsuarioChar91idChar93InstrumentosIndexRoute
  '/usuario/$id/reportes': typeof UsuarioChar91idChar93ReportesIndexRoute
  '/usuario/$id/reportes/$reporteId': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteWithChildren
  '/usuario/$id/reportes/$reporteId/pdf': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRoute
  '/usuario/$id/reportes/$reporteId/pdf-reducida': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRoute
  '/usuario/$id/reportes/$reporteId/areas': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRoute
  '/usuario/$id/reportes/$reporteId/general': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRoute
  '/usuario/$id/reportes/$reporteId/resumen': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files': typeof FilesRouteRouteWithChildren
  '/reportes': typeof ReportesRouteRouteWithChildren
  '/usuario': typeof UsuarioRouteRouteWithChildren
  '/usuario/$id': typeof UsuarioChar91idChar93RouteRouteWithChildren
  '/files/': typeof FilesIndexRoute
  '/money/': typeof MoneyIndexRoute
  '/reportes/': typeof ReportesIndexRoute
  '/usuario/': typeof UsuarioIndexRoute
  '/files/repetidas/': typeof FilesRepetidasIndexRoute
  '/files/tecnicos/': typeof FilesTecnicosIndexRoute
  '/files/unused/': typeof FilesUnusedIndexRoute
  '/usuario/$id/': typeof UsuarioChar91idChar93IndexRoute
  '/usuario/$id/creditos/': typeof UsuarioChar91idChar93CreditosIndexRoute
  '/usuario/$id/empresas/': typeof UsuarioChar91idChar93EmpresasIndexRoute
  '/usuario/$id/instrumentos/': typeof UsuarioChar91idChar93InstrumentosIndexRoute
  '/usuario/$id/reportes/': typeof UsuarioChar91idChar93ReportesIndexRoute
  '/usuario/$id/reportes/$reporteId/_header': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteWithChildren
  '/usuario/$id/reportes/$reporteId/pdf': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRoute
  '/usuario/$id/reportes/$reporteId/pdf-reducida': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRoute
  '/usuario/$id/reportes/$reporteId/_header/areas/': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRoute
  '/usuario/$id/reportes/$reporteId/_header/general/': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRoute
  '/usuario/$id/reportes/$reporteId/_header/resumen/': typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/reportes'
    | '/usuario'
    | '/usuario/$id'
    | '/files/'
    | '/money/'
    | '/reportes/'
    | '/usuario/'
    | '/files/repetidas/'
    | '/files/tecnicos/'
    | '/files/unused/'
    | '/usuario/$id/'
    | '/usuario/$id/creditos/'
    | '/usuario/$id/empresas/'
    | '/usuario/$id/instrumentos/'
    | '/usuario/$id/reportes/'
    | '/usuario/$id/reportes/$reporteId'
    | '/usuario/$id/reportes/$reporteId/pdf'
    | '/usuario/$id/reportes/$reporteId/pdf-reducida'
    | '/usuario/$id/reportes/$reporteId/areas/'
    | '/usuario/$id/reportes/$reporteId/general/'
    | '/usuario/$id/reportes/$reporteId/resumen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/money'
    | '/reportes'
    | '/usuario'
    | '/files/repetidas'
    | '/files/tecnicos'
    | '/files/unused'
    | '/usuario/$id'
    | '/usuario/$id/creditos'
    | '/usuario/$id/empresas'
    | '/usuario/$id/instrumentos'
    | '/usuario/$id/reportes'
    | '/usuario/$id/reportes/$reporteId'
    | '/usuario/$id/reportes/$reporteId/pdf'
    | '/usuario/$id/reportes/$reporteId/pdf-reducida'
    | '/usuario/$id/reportes/$reporteId/areas'
    | '/usuario/$id/reportes/$reporteId/general'
    | '/usuario/$id/reportes/$reporteId/resumen'
  id:
    | '__root__'
    | '/'
    | '/files'
    | '/reportes'
    | '/usuario'
    | '/usuario/$id'
    | '/files/'
    | '/money/'
    | '/reportes/'
    | '/usuario/'
    | '/files/repetidas/'
    | '/files/tecnicos/'
    | '/files/unused/'
    | '/usuario/$id/'
    | '/usuario/$id/creditos/'
    | '/usuario/$id/empresas/'
    | '/usuario/$id/instrumentos/'
    | '/usuario/$id/reportes/'
    | '/usuario/$id/reportes/$reporteId/_header'
    | '/usuario/$id/reportes/$reporteId/pdf'
    | '/usuario/$id/reportes/$reporteId/pdf-reducida'
    | '/usuario/$id/reportes/$reporteId/_header/areas/'
    | '/usuario/$id/reportes/$reporteId/_header/general/'
    | '/usuario/$id/reportes/$reporteId/_header/resumen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesRouteRoute: typeof FilesRouteRouteWithChildren
  ReportesRouteRoute: typeof ReportesRouteRouteWithChildren
  UsuarioRouteRoute: typeof UsuarioRouteRouteWithChildren
  MoneyIndexRoute: typeof MoneyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuario': {
      id: '/usuario'
      path: '/usuario'
      fullPath: '/usuario'
      preLoaderRoute: typeof UsuarioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuario/': {
      id: '/usuario/'
      path: '/'
      fullPath: '/usuario/'
      preLoaderRoute: typeof UsuarioIndexRouteImport
      parentRoute: typeof UsuarioRouteRoute
    }
    '/reportes/': {
      id: '/reportes/'
      path: '/'
      fullPath: '/reportes/'
      preLoaderRoute: typeof ReportesIndexRouteImport
      parentRoute: typeof ReportesRouteRoute
    }
    '/money/': {
      id: '/money/'
      path: '/money'
      fullPath: '/money/'
      preLoaderRoute: typeof MoneyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof FilesRouteRoute
    }
    '/usuario/$id': {
      id: '/usuario/$id'
      path: '/$id'
      fullPath: '/usuario/$id'
      preLoaderRoute: typeof UsuarioChar91idChar93RouteRouteImport
      parentRoute: typeof UsuarioRouteRoute
    }
    '/usuario/$id/': {
      id: '/usuario/$id/'
      path: '/'
      fullPath: '/usuario/$id/'
      preLoaderRoute: typeof UsuarioChar91idChar93IndexRouteImport
      parentRoute: typeof UsuarioChar91idChar93RouteRoute
    }
    '/files/unused/': {
      id: '/files/unused/'
      path: '/unused'
      fullPath: '/files/unused/'
      preLoaderRoute: typeof FilesUnusedIndexRouteImport
      parentRoute: typeof FilesRouteRoute
    }
    '/files/tecnicos/': {
      id: '/files/tecnicos/'
      path: '/tecnicos'
      fullPath: '/files/tecnicos/'
      preLoaderRoute: typeof FilesTecnicosIndexRouteImport
      parentRoute: typeof FilesRouteRoute
    }
    '/files/repetidas/': {
      id: '/files/repetidas/'
      path: '/repetidas'
      fullPath: '/files/repetidas/'
      preLoaderRoute: typeof FilesRepetidasIndexRouteImport
      parentRoute: typeof FilesRouteRoute
    }
    '/usuario/$id/reportes/': {
      id: '/usuario/$id/reportes/'
      path: '/reportes'
      fullPath: '/usuario/$id/reportes/'
      preLoaderRoute: typeof UsuarioChar91idChar93ReportesIndexRouteImport
      parentRoute: typeof UsuarioChar91idChar93RouteRoute
    }
    '/usuario/$id/instrumentos/': {
      id: '/usuario/$id/instrumentos/'
      path: '/instrumentos'
      fullPath: '/usuario/$id/instrumentos/'
      preLoaderRoute: typeof UsuarioChar91idChar93InstrumentosIndexRouteImport
      parentRoute: typeof UsuarioChar91idChar93RouteRoute
    }
    '/usuario/$id/empresas/': {
      id: '/usuario/$id/empresas/'
      path: '/empresas'
      fullPath: '/usuario/$id/empresas/'
      preLoaderRoute: typeof UsuarioChar91idChar93EmpresasIndexRouteImport
      parentRoute: typeof UsuarioChar91idChar93RouteRoute
    }
    '/usuario/$id/creditos/': {
      id: '/usuario/$id/creditos/'
      path: '/creditos'
      fullPath: '/usuario/$id/creditos/'
      preLoaderRoute: typeof UsuarioChar91idChar93CreditosIndexRouteImport
      parentRoute: typeof UsuarioChar91idChar93RouteRoute
    }
    '/usuario/$id/reportes/$reporteId/pdf-reducida': {
      id: '/usuario/$id/reportes/$reporteId/pdf-reducida'
      path: '/reportes/$reporteId/pdf-reducida'
      fullPath: '/usuario/$id/reportes/$reporteId/pdf-reducida'
      preLoaderRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRouteImport
      parentRoute: typeof UsuarioChar91idChar93RouteRoute
    }
    '/usuario/$id/reportes/$reporteId/pdf': {
      id: '/usuario/$id/reportes/$reporteId/pdf'
      path: '/reportes/$reporteId/pdf'
      fullPath: '/usuario/$id/reportes/$reporteId/pdf'
      preLoaderRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRouteImport
      parentRoute: typeof UsuarioChar91idChar93RouteRoute
    }
    '/usuario/$id/reportes/$reporteId/_header': {
      id: '/usuario/$id/reportes/$reporteId/_header'
      path: '/reportes/$reporteId'
      fullPath: '/usuario/$id/reportes/$reporteId'
      preLoaderRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteImport
      parentRoute: typeof UsuarioChar91idChar93RouteRoute
    }
    '/usuario/$id/reportes/$reporteId/_header/resumen/': {
      id: '/usuario/$id/reportes/$reporteId/_header/resumen/'
      path: '/resumen'
      fullPath: '/usuario/$id/reportes/$reporteId/resumen/'
      preLoaderRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRouteImport
      parentRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRoute
    }
    '/usuario/$id/reportes/$reporteId/_header/general/': {
      id: '/usuario/$id/reportes/$reporteId/_header/general/'
      path: '/general'
      fullPath: '/usuario/$id/reportes/$reporteId/general/'
      preLoaderRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRouteImport
      parentRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRoute
    }
    '/usuario/$id/reportes/$reporteId/_header/areas/': {
      id: '/usuario/$id/reportes/$reporteId/_header/areas/'
      path: '/areas'
      fullPath: '/usuario/$id/reportes/$reporteId/areas/'
      preLoaderRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRouteImport
      parentRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRoute
    }
  }
}

interface FilesRouteRouteChildren {
  FilesIndexRoute: typeof FilesIndexRoute
  FilesRepetidasIndexRoute: typeof FilesRepetidasIndexRoute
  FilesTecnicosIndexRoute: typeof FilesTecnicosIndexRoute
  FilesUnusedIndexRoute: typeof FilesUnusedIndexRoute
}

const FilesRouteRouteChildren: FilesRouteRouteChildren = {
  FilesIndexRoute: FilesIndexRoute,
  FilesRepetidasIndexRoute: FilesRepetidasIndexRoute,
  FilesTecnicosIndexRoute: FilesTecnicosIndexRoute,
  FilesUnusedIndexRoute: FilesUnusedIndexRoute,
}

const FilesRouteRouteWithChildren = FilesRouteRoute._addFileChildren(
  FilesRouteRouteChildren,
)

interface ReportesRouteRouteChildren {
  ReportesIndexRoute: typeof ReportesIndexRoute
}

const ReportesRouteRouteChildren: ReportesRouteRouteChildren = {
  ReportesIndexRoute: ReportesIndexRoute,
}

const ReportesRouteRouteWithChildren = ReportesRouteRoute._addFileChildren(
  ReportesRouteRouteChildren,
)

interface UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteChildren {
  UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRoute
  UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRoute
  UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRoute
}

const UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteChildren: UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteChildren =
  {
    UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRoute:
      UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderAreasIndexRoute,
    UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRoute:
      UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderGeneralIndexRoute,
    UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRoute:
      UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderResumenIndexRoute,
  }

const UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteWithChildren =
  UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRoute._addFileChildren(
    UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteChildren,
  )

interface UsuarioChar91idChar93RouteRouteChildren {
  UsuarioChar91idChar93IndexRoute: typeof UsuarioChar91idChar93IndexRoute
  UsuarioChar91idChar93CreditosIndexRoute: typeof UsuarioChar91idChar93CreditosIndexRoute
  UsuarioChar91idChar93EmpresasIndexRoute: typeof UsuarioChar91idChar93EmpresasIndexRoute
  UsuarioChar91idChar93InstrumentosIndexRoute: typeof UsuarioChar91idChar93InstrumentosIndexRoute
  UsuarioChar91idChar93ReportesIndexRoute: typeof UsuarioChar91idChar93ReportesIndexRoute
  UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteWithChildren
  UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRoute
  UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRoute: typeof UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRoute
}

const UsuarioChar91idChar93RouteRouteChildren: UsuarioChar91idChar93RouteRouteChildren =
  {
    UsuarioChar91idChar93IndexRoute: UsuarioChar91idChar93IndexRoute,
    UsuarioChar91idChar93CreditosIndexRoute:
      UsuarioChar91idChar93CreditosIndexRoute,
    UsuarioChar91idChar93EmpresasIndexRoute:
      UsuarioChar91idChar93EmpresasIndexRoute,
    UsuarioChar91idChar93InstrumentosIndexRoute:
      UsuarioChar91idChar93InstrumentosIndexRoute,
    UsuarioChar91idChar93ReportesIndexRoute:
      UsuarioChar91idChar93ReportesIndexRoute,
    UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRoute:
      UsuarioChar91idChar93ReportesChar91reporteIdChar93HeaderRouteRouteWithChildren,
    UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRoute:
      UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfRoute,
    UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRoute:
      UsuarioChar91idChar93ReportesChar91reporteIdChar93PdfReducidaRoute,
  }

const UsuarioChar91idChar93RouteRouteWithChildren =
  UsuarioChar91idChar93RouteRoute._addFileChildren(
    UsuarioChar91idChar93RouteRouteChildren,
  )

interface UsuarioRouteRouteChildren {
  UsuarioChar91idChar93RouteRoute: typeof UsuarioChar91idChar93RouteRouteWithChildren
  UsuarioIndexRoute: typeof UsuarioIndexRoute
}

const UsuarioRouteRouteChildren: UsuarioRouteRouteChildren = {
  UsuarioChar91idChar93RouteRoute: UsuarioChar91idChar93RouteRouteWithChildren,
  UsuarioIndexRoute: UsuarioIndexRoute,
}

const UsuarioRouteRouteWithChildren = UsuarioRouteRoute._addFileChildren(
  UsuarioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesRouteRoute: FilesRouteRouteWithChildren,
  ReportesRouteRoute: ReportesRouteRouteWithChildren,
  UsuarioRouteRoute: UsuarioRouteRouteWithChildren,
  MoneyIndexRoute: MoneyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
