/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FilesRouteRouteImport } from './routes/files/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardChar91idChar93RouteRouteImport } from './routes/dashboard/[$id]/route'
import { Route as FilesUnusedIndexRouteImport } from './routes/files/unused.index'
import { Route as FilesTecnicosIndexRouteImport } from './routes/files/tecnicos.index'
import { Route as DashboardChar91idChar93IndexRouteImport } from './routes/dashboard/[$id]/index'
import { Route as DashboardChar91idChar93ReportesIndexRouteImport } from './routes/dashboard/[$id]/reportes.index'
import { Route as DashboardChar91idChar93InstrumentosIndexRouteImport } from './routes/dashboard/[$id]/instrumentos.index'
import { Route as DashboardChar91idChar93EmpresasIndexRouteImport } from './routes/dashboard/[$id]/empresas.index'
import { Route as DashboardChar91idChar93ReporteReporteNuevoIndexRouteImport } from './routes/dashboard/[$id]/reporte/reporte-nuevo/index'
import { Route as DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRouteImport } from './routes/dashboard/[$id]/reporte/[$reporteId]/pdf'
import { Route as DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteImport } from './routes/dashboard/[$id]/reporte/[$reporteId]/_header/route'
import { Route as DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRouteImport } from './routes/dashboard/[$id]/reporte/[$reporteId]/_header/resumen.index'
import { Route as DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRouteImport } from './routes/dashboard/[$id]/reporte/[$reporteId]/_header/general.index'
import { Route as DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRouteImport } from './routes/dashboard/[$id]/reporte/[$reporteId]/_header/areas.index'

const FilesRouteRoute = FilesRouteRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilesRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChar91idChar93RouteRoute =
  DashboardChar91idChar93RouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const FilesUnusedIndexRoute = FilesUnusedIndexRouteImport.update({
  id: '/unused/',
  path: '/unused/',
  getParentRoute: () => FilesRouteRoute,
} as any)
const FilesTecnicosIndexRoute = FilesTecnicosIndexRouteImport.update({
  id: '/tecnicos/',
  path: '/tecnicos/',
  getParentRoute: () => FilesRouteRoute,
} as any)
const DashboardChar91idChar93IndexRoute =
  DashboardChar91idChar93IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardChar91idChar93RouteRoute,
  } as any)
const DashboardChar91idChar93ReportesIndexRoute =
  DashboardChar91idChar93ReportesIndexRouteImport.update({
    id: '/reportes/',
    path: '/reportes/',
    getParentRoute: () => DashboardChar91idChar93RouteRoute,
  } as any)
const DashboardChar91idChar93InstrumentosIndexRoute =
  DashboardChar91idChar93InstrumentosIndexRouteImport.update({
    id: '/instrumentos/',
    path: '/instrumentos/',
    getParentRoute: () => DashboardChar91idChar93RouteRoute,
  } as any)
const DashboardChar91idChar93EmpresasIndexRoute =
  DashboardChar91idChar93EmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => DashboardChar91idChar93RouteRoute,
  } as any)
const DashboardChar91idChar93ReporteReporteNuevoIndexRoute =
  DashboardChar91idChar93ReporteReporteNuevoIndexRouteImport.update({
    id: '/reporte/reporte-nuevo/',
    path: '/reporte/reporte-nuevo/',
    getParentRoute: () => DashboardChar91idChar93RouteRoute,
  } as any)
const DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRoute =
  DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRouteImport.update({
    id: '/reporte/$reporteId/pdf',
    path: '/reporte/$reporteId/pdf',
    getParentRoute: () => DashboardChar91idChar93RouteRoute,
  } as any)
const DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRoute =
  DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteImport.update(
    {
      id: '/reporte/$reporteId/_header',
      path: '/reporte/$reporteId',
      getParentRoute: () => DashboardChar91idChar93RouteRoute,
    } as any,
  )
const DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRoute =
  DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRouteImport.update(
    {
      id: '/resumen/',
      path: '/resumen/',
      getParentRoute: () =>
        DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRoute,
    } as any,
  )
const DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRoute =
  DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRouteImport.update(
    {
      id: '/general/',
      path: '/general/',
      getParentRoute: () =>
        DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRoute,
    } as any,
  )
const DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRoute =
  DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRouteImport.update(
    {
      id: '/areas/',
      path: '/areas/',
      getParentRoute: () =>
        DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/files': typeof FilesRouteRouteWithChildren
  '/dashboard/$id': typeof DashboardChar91idChar93RouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/files/': typeof FilesIndexRoute
  '/dashboard/$id/': typeof DashboardChar91idChar93IndexRoute
  '/files/tecnicos/': typeof FilesTecnicosIndexRoute
  '/files/unused/': typeof FilesUnusedIndexRoute
  '/dashboard/$id/empresas/': typeof DashboardChar91idChar93EmpresasIndexRoute
  '/dashboard/$id/instrumentos/': typeof DashboardChar91idChar93InstrumentosIndexRoute
  '/dashboard/$id/reportes/': typeof DashboardChar91idChar93ReportesIndexRoute
  '/dashboard/$id/reporte/$reporteId': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteWithChildren
  '/dashboard/$id/reporte/$reporteId/pdf': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRoute
  '/dashboard/$id/reporte/reporte-nuevo/': typeof DashboardChar91idChar93ReporteReporteNuevoIndexRoute
  '/dashboard/$id/reporte/$reporteId/areas/': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRoute
  '/dashboard/$id/reporte/$reporteId/general/': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRoute
  '/dashboard/$id/reporte/$reporteId/resumen/': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/files': typeof FilesIndexRoute
  '/dashboard/$id': typeof DashboardChar91idChar93IndexRoute
  '/files/tecnicos': typeof FilesTecnicosIndexRoute
  '/files/unused': typeof FilesUnusedIndexRoute
  '/dashboard/$id/empresas': typeof DashboardChar91idChar93EmpresasIndexRoute
  '/dashboard/$id/instrumentos': typeof DashboardChar91idChar93InstrumentosIndexRoute
  '/dashboard/$id/reportes': typeof DashboardChar91idChar93ReportesIndexRoute
  '/dashboard/$id/reporte/$reporteId': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteWithChildren
  '/dashboard/$id/reporte/$reporteId/pdf': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRoute
  '/dashboard/$id/reporte/reporte-nuevo': typeof DashboardChar91idChar93ReporteReporteNuevoIndexRoute
  '/dashboard/$id/reporte/$reporteId/areas': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRoute
  '/dashboard/$id/reporte/$reporteId/general': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRoute
  '/dashboard/$id/reporte/$reporteId/resumen': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/files': typeof FilesRouteRouteWithChildren
  '/dashboard/$id': typeof DashboardChar91idChar93RouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/files/': typeof FilesIndexRoute
  '/dashboard/$id/': typeof DashboardChar91idChar93IndexRoute
  '/files/tecnicos/': typeof FilesTecnicosIndexRoute
  '/files/unused/': typeof FilesUnusedIndexRoute
  '/dashboard/$id/empresas/': typeof DashboardChar91idChar93EmpresasIndexRoute
  '/dashboard/$id/instrumentos/': typeof DashboardChar91idChar93InstrumentosIndexRoute
  '/dashboard/$id/reportes/': typeof DashboardChar91idChar93ReportesIndexRoute
  '/dashboard/$id/reporte/$reporteId/_header': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteWithChildren
  '/dashboard/$id/reporte/$reporteId/pdf': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRoute
  '/dashboard/$id/reporte/reporte-nuevo/': typeof DashboardChar91idChar93ReporteReporteNuevoIndexRoute
  '/dashboard/$id/reporte/$reporteId/_header/areas/': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRoute
  '/dashboard/$id/reporte/$reporteId/_header/general/': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRoute
  '/dashboard/$id/reporte/$reporteId/_header/resumen/': typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/files'
    | '/dashboard/$id'
    | '/dashboard/'
    | '/files/'
    | '/dashboard/$id/'
    | '/files/tecnicos/'
    | '/files/unused/'
    | '/dashboard/$id/empresas/'
    | '/dashboard/$id/instrumentos/'
    | '/dashboard/$id/reportes/'
    | '/dashboard/$id/reporte/$reporteId'
    | '/dashboard/$id/reporte/$reporteId/pdf'
    | '/dashboard/$id/reporte/reporte-nuevo/'
    | '/dashboard/$id/reporte/$reporteId/areas/'
    | '/dashboard/$id/reporte/$reporteId/general/'
    | '/dashboard/$id/reporte/$reporteId/resumen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/files'
    | '/dashboard/$id'
    | '/files/tecnicos'
    | '/files/unused'
    | '/dashboard/$id/empresas'
    | '/dashboard/$id/instrumentos'
    | '/dashboard/$id/reportes'
    | '/dashboard/$id/reporte/$reporteId'
    | '/dashboard/$id/reporte/$reporteId/pdf'
    | '/dashboard/$id/reporte/reporte-nuevo'
    | '/dashboard/$id/reporte/$reporteId/areas'
    | '/dashboard/$id/reporte/$reporteId/general'
    | '/dashboard/$id/reporte/$reporteId/resumen'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/files'
    | '/dashboard/$id'
    | '/dashboard/'
    | '/files/'
    | '/dashboard/$id/'
    | '/files/tecnicos/'
    | '/files/unused/'
    | '/dashboard/$id/empresas/'
    | '/dashboard/$id/instrumentos/'
    | '/dashboard/$id/reportes/'
    | '/dashboard/$id/reporte/$reporteId/_header'
    | '/dashboard/$id/reporte/$reporteId/pdf'
    | '/dashboard/$id/reporte/reporte-nuevo/'
    | '/dashboard/$id/reporte/$reporteId/_header/areas/'
    | '/dashboard/$id/reporte/$reporteId/_header/general/'
    | '/dashboard/$id/reporte/$reporteId/_header/resumen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  FilesRouteRoute: typeof FilesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof FilesRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardChar91idChar93RouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/files/unused/': {
      id: '/files/unused/'
      path: '/unused'
      fullPath: '/files/unused/'
      preLoaderRoute: typeof FilesUnusedIndexRouteImport
      parentRoute: typeof FilesRouteRoute
    }
    '/files/tecnicos/': {
      id: '/files/tecnicos/'
      path: '/tecnicos'
      fullPath: '/files/tecnicos/'
      preLoaderRoute: typeof FilesTecnicosIndexRouteImport
      parentRoute: typeof FilesRouteRoute
    }
    '/dashboard/$id/': {
      id: '/dashboard/$id/'
      path: '/'
      fullPath: '/dashboard/$id/'
      preLoaderRoute: typeof DashboardChar91idChar93IndexRouteImport
      parentRoute: typeof DashboardChar91idChar93RouteRoute
    }
    '/dashboard/$id/reportes/': {
      id: '/dashboard/$id/reportes/'
      path: '/reportes'
      fullPath: '/dashboard/$id/reportes/'
      preLoaderRoute: typeof DashboardChar91idChar93ReportesIndexRouteImport
      parentRoute: typeof DashboardChar91idChar93RouteRoute
    }
    '/dashboard/$id/instrumentos/': {
      id: '/dashboard/$id/instrumentos/'
      path: '/instrumentos'
      fullPath: '/dashboard/$id/instrumentos/'
      preLoaderRoute: typeof DashboardChar91idChar93InstrumentosIndexRouteImport
      parentRoute: typeof DashboardChar91idChar93RouteRoute
    }
    '/dashboard/$id/empresas/': {
      id: '/dashboard/$id/empresas/'
      path: '/empresas'
      fullPath: '/dashboard/$id/empresas/'
      preLoaderRoute: typeof DashboardChar91idChar93EmpresasIndexRouteImport
      parentRoute: typeof DashboardChar91idChar93RouteRoute
    }
    '/dashboard/$id/reporte/reporte-nuevo/': {
      id: '/dashboard/$id/reporte/reporte-nuevo/'
      path: '/reporte/reporte-nuevo'
      fullPath: '/dashboard/$id/reporte/reporte-nuevo/'
      preLoaderRoute: typeof DashboardChar91idChar93ReporteReporteNuevoIndexRouteImport
      parentRoute: typeof DashboardChar91idChar93RouteRoute
    }
    '/dashboard/$id/reporte/$reporteId/pdf': {
      id: '/dashboard/$id/reporte/$reporteId/pdf'
      path: '/reporte/$reporteId/pdf'
      fullPath: '/dashboard/$id/reporte/$reporteId/pdf'
      preLoaderRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRouteImport
      parentRoute: typeof DashboardChar91idChar93RouteRoute
    }
    '/dashboard/$id/reporte/$reporteId/_header': {
      id: '/dashboard/$id/reporte/$reporteId/_header'
      path: '/reporte/$reporteId'
      fullPath: '/dashboard/$id/reporte/$reporteId'
      preLoaderRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteImport
      parentRoute: typeof DashboardChar91idChar93RouteRoute
    }
    '/dashboard/$id/reporte/$reporteId/_header/resumen/': {
      id: '/dashboard/$id/reporte/$reporteId/_header/resumen/'
      path: '/resumen'
      fullPath: '/dashboard/$id/reporte/$reporteId/resumen/'
      preLoaderRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRouteImport
      parentRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRoute
    }
    '/dashboard/$id/reporte/$reporteId/_header/general/': {
      id: '/dashboard/$id/reporte/$reporteId/_header/general/'
      path: '/general'
      fullPath: '/dashboard/$id/reporte/$reporteId/general/'
      preLoaderRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRouteImport
      parentRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRoute
    }
    '/dashboard/$id/reporte/$reporteId/_header/areas/': {
      id: '/dashboard/$id/reporte/$reporteId/_header/areas/'
      path: '/areas'
      fullPath: '/dashboard/$id/reporte/$reporteId/areas/'
      preLoaderRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRouteImport
      parentRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRoute
    }
  }
}

interface DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteChildren {
  DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRoute
  DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRoute
  DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRoute
}

const DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteChildren: DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteChildren =
  {
    DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRoute:
      DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderAreasIndexRoute,
    DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRoute:
      DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderGeneralIndexRoute,
    DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRoute:
      DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderResumenIndexRoute,
  }

const DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteWithChildren =
  DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRoute._addFileChildren(
    DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteChildren,
  )

interface DashboardChar91idChar93RouteRouteChildren {
  DashboardChar91idChar93IndexRoute: typeof DashboardChar91idChar93IndexRoute
  DashboardChar91idChar93EmpresasIndexRoute: typeof DashboardChar91idChar93EmpresasIndexRoute
  DashboardChar91idChar93InstrumentosIndexRoute: typeof DashboardChar91idChar93InstrumentosIndexRoute
  DashboardChar91idChar93ReportesIndexRoute: typeof DashboardChar91idChar93ReportesIndexRoute
  DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteWithChildren
  DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRoute: typeof DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRoute
  DashboardChar91idChar93ReporteReporteNuevoIndexRoute: typeof DashboardChar91idChar93ReporteReporteNuevoIndexRoute
}

const DashboardChar91idChar93RouteRouteChildren: DashboardChar91idChar93RouteRouteChildren =
  {
    DashboardChar91idChar93IndexRoute: DashboardChar91idChar93IndexRoute,
    DashboardChar91idChar93EmpresasIndexRoute:
      DashboardChar91idChar93EmpresasIndexRoute,
    DashboardChar91idChar93InstrumentosIndexRoute:
      DashboardChar91idChar93InstrumentosIndexRoute,
    DashboardChar91idChar93ReportesIndexRoute:
      DashboardChar91idChar93ReportesIndexRoute,
    DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRoute:
      DashboardChar91idChar93ReporteChar91reporteIdChar93HeaderRouteRouteWithChildren,
    DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRoute:
      DashboardChar91idChar93ReporteChar91reporteIdChar93PdfRoute,
    DashboardChar91idChar93ReporteReporteNuevoIndexRoute:
      DashboardChar91idChar93ReporteReporteNuevoIndexRoute,
  }

const DashboardChar91idChar93RouteRouteWithChildren =
  DashboardChar91idChar93RouteRoute._addFileChildren(
    DashboardChar91idChar93RouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardChar91idChar93RouteRoute: typeof DashboardChar91idChar93RouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardChar91idChar93RouteRoute:
    DashboardChar91idChar93RouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface FilesRouteRouteChildren {
  FilesIndexRoute: typeof FilesIndexRoute
  FilesTecnicosIndexRoute: typeof FilesTecnicosIndexRoute
  FilesUnusedIndexRoute: typeof FilesUnusedIndexRoute
}

const FilesRouteRouteChildren: FilesRouteRouteChildren = {
  FilesIndexRoute: FilesIndexRoute,
  FilesTecnicosIndexRoute: FilesTecnicosIndexRoute,
  FilesUnusedIndexRoute: FilesUnusedIndexRoute,
}

const FilesRouteRouteWithChildren = FilesRouteRoute._addFileChildren(
  FilesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  FilesRouteRoute: FilesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
